yatube/about/urls.py
"""Urls приложения about"""

from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
"""Urls приложения Posts."""

from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'posts'

urlpatterns = [
    path(
            '',
            cache_page(20)(views.IndexView.as_view()),
            name='index'
    ),
    path(
            'group/<slug:slug>/',
            views.GroupPostsView.as_view(),
            name='group_list'
    ),
    path(
            'profile/<str:username>/',
            views.ProfileView.as_view(),
            name='profile'
    ),
    path(
            'posts/<int:pk>/',
            views.PostDetailView.as_view(),
            name='post_detail'
    ),
    path(
            'create/',
            views.PostCreateView.as_view(),
            name='post_create'
    ),
    path(
            'posts/<int:pk>/edit/',
            views.PostEditView.as_view(),
            name='post_edit'
    ),
    path(
            'posts/<int:pk>/comment/',
            views.AddCommentFormView.as_view(),
            name='add_comment'
    ),
    path(
            'follow/',
            views.FollowView.as_view(),
            name='follow_index'
    ),
    path(
            'profile/<str:username>/follow/',
            views.FollowAuthorView.as_view(),
            name='profile_follow'
    ),
    path(
            'profile/<str:username>/unfollow/',
            views.UnfollowAuthorView.as_view(),
            name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls')),
    path('about/', include('about.urls')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      {# {% url 'posts:add_comment' post.id %} #}
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group mb-2">
            {{ field.label_tag }}
            {{ field|addclass:'form-control' }}
            {% if field.errors %}
              <div class="alert alert-danger" role="alert">
                {% for error in field.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% endif %}
          </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
{% block footer %}
    <footer class="border-top text-center py-3">
        <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
{% endblock footer %}

yatube/templates/includes/header.html
{% load static %}
{% block header %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30"
             class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link
              {% if view_name == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
              {% if view_name == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link
                {% if view_name == 'posts:post_create' %}active{% endif %}"
               href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light
                {% if view_name == 'users:password_change' %}active{% endif %}"
              href="{% url 'users:password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light
                {% if view_name == 'users:logout' %}active{% endif %}"
              href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="javascript: void(0);">
              Пользователь: {{ user.username }}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a
              class="nav-link link-light
                {% if view_name == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link link-light
                {% if view_name == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      {% endwith %}
      </ul>
    </div>
  </nav>
{% endblock header %}