yatube/about/urls.py
"""Urls приложения about"""

from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
"""Urls приложения Posts."""

from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'posts'

urlpatterns = [
    path(
            '',
            cache_page(20)(views.IndexView.as_view()),
            name='index'
    ),
    path(
            'group/<slug:slug>/',
            views.GroupPostsView.as_view(),
            name='group_list'
    ),
    path(
            'profile/<str:username>/',
            views.ProfileView.as_view(),
            name='profile'
    ),
    path(
            'posts/<int:pk>/',
            views.PostDetailView.as_view(),
            name='post_detail'
    ),
    path(
            'create/',
            views.PostCreateView.as_view(),
            name='post_create'
    ),
    path(
            'posts/<int:pk>/edit/',
            views.PostEditView.as_view(),
            name='post_edit'
    ),
    path(
            'posts/<int:pk>/comment/',
            views.AddCommentFormView.as_view(),
            name='add_comment'
    ),
    path(
            'follow/',
            views.FollowView.as_view(),
            name='follow_index'
    ),
    path(
            'profile/<str:username>/follow/',
            views.FollowAuthorView.as_view(),
            name='profile_follow'
    ),
    path(
            'profile/<str:username>/unfollow/',
            views.UnfollowAuthorView.as_view(),
            name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls')),
    path('about/', include('about.urls')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
"""Модели приложения Posts."""
from django.contrib.auth import get_user_model
from django.db import models
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """ Модель групп"""
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, db_index=True, verbose_name="URL")
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """Модель постов"""
    text = models.TextField(
            'Текст поста',
            help_text='Введите текст поста'
    )
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='posts',
            verbose_name='Автор'
    )
    group = models.ForeignKey(
            Group,
            on_delete=models.SET_NULL,
            related_name='posts',
            blank=True,
            null=True,
            verbose_name='Группа',
            help_text='Группа, к которой относится пост'
    )
    image = models.ImageField(
            'Картинка',
            upload_to='posts/',
            blank=True
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comments(CreatedModel):
    """Модель комментариев."""
    post = models.ForeignKey(
            Post,
            verbose_name='Пост',
            help_text='Ссылка на пост',
            on_delete=models.CASCADE,
            related_name='comments'
    )
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='comments',
            verbose_name='Автор'
    )
    text = models.CharField(
            max_length=350,
            verbose_name='Текст комментария',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    """Модель подписок."""
    user = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='follower',
            verbose_name='Пользователь',
    )
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='following',
            verbose_name='Автор',
            help_text='На какого автора подписан пользователь'
    )

yatube/posts/forms.py
"""Формы приложения posts."""

from django import forms
from .models import Post, Comments


class PostForm(forms.ModelForm):
    """Форма создания/редактирования постов."""
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Форма создания комментария."""
    class Meta:
        model = Comments
        fields = ('text',)

yatube/posts/views.py
"""Views приложения posts."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, FormView, ListView, \
    RedirectView, UpdateView

from .forms import CommentForm, PostForm
from .models import Comments, Follow, Group, Post, User


class IndexView(ListView):
    """Главная страница."""
    model = Post
    template_name = 'posts/index.html'
    paginate_by = 10
    context_object_name = 'post_list'

    def get_queryset(self):
        queryset = super().get_queryset().select_related('author', 'group')
        return queryset


class GroupPostsView(ListView):
    """Посты по группам."""
    model = Post
    template_name = 'posts/group_list.html'
    paginate_by = 10
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(
                group__slug=self.kwargs['slug']
        ).select_related('author', 'group')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = get_object_or_404(Group, slug=self.kwargs['slug'])
        context['group'] = group
        return context


class ProfileView(ListView):
    """Профайл пользователя."""
    model = Post
    template_name = 'posts/profile.html'
    paginate_by = 10
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(
                author__username=self.kwargs['username']
        ).select_related(
                'author',
                'group'
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        author = User.objects.get(username=self.kwargs['username'])

        following = Follow.objects.filter(
                user=self.request.user,
                author=author
        ).exists()

        context['post_count'] = self.get_queryset().count()
        context['author'] = author
        context['following'] = following
        return context


class PostDetailView(DetailView):
    """Страница детального просмотра поста."""
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        comments = Comments.objects.filter(
                post_id=self.object.pk
        ).select_related('author')

        posts_count = Post.objects.filter(
                author=self.object.author
        ).count()

        context['comments'] = comments
        context['form'] = CommentForm()
        context['posts_count'] = posts_count
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    """Страница создания поста."""
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = False
        return context

    def get_success_url(self):
        return reverse_lazy(
                'posts:profile',
                kwargs={'username': self.request.user.username}
        )


class PostEditView(LoginRequiredMixin, UpdateView):
    """Страница редактирования поста."""
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if post.author != self.request.user:
            return redirect('posts:post_detail', pk=post.pk)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return self.get_success_url()

    def get_success_url(self):
        return redirect(
                'posts:profile',
                username=self.request.user.username
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['is_edit'] = True
        return context


class AddCommentFormView(LoginRequiredMixin, FormView):
    """Добавление комментариев."""
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = Post.objects.get(pk=self.kwargs['pk'])
        comment.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class FollowView(LoginRequiredMixin, ListView):
    """Страница подписок пользователя"""
    template_name = 'posts/follow.html'
    model = Post
    paginate_by = 10

    def get_queryset(self):
        follows = Follow.objects.filter(
                user_id=self.request.user
        ).select_related('author', 'user')

        authors = [follow.author for follow in follows]
        return Post.objects.filter(
                author_id__in=authors
        ).select_related('group', 'author')


class FollowAuthorView(LoginRequiredMixin, RedirectView):
    """Подписка на автора."""

    def get_redirect_url(self, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs['username'])
        follow = Follow.objects.get_or_create(
                user_id=self.request.user.id,
                author_id=author.id
        )
        print(follow)
        return reverse('posts:profile', kwargs={'username': author.username})


class UnfollowAuthorView(LoginRequiredMixin, RedirectView):
    """Отписка от автора."""
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs['username'])
        Follow.objects.filter(user=self.request.user, author=author).delete()
        return reverse('posts:profile', kwargs={'username': author.username})

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактирование записи
  {% else %}
    Создание новой записи
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактирование поста
            {% else %}
              Новая запись
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.label }}">{{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:"form-control" }}
                  <small id="{{ field.help_text }}"
                         class="form-text text-muted">
                    {{ field.help_text }}</small>
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock title %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% if page_obj %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи
            группы</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% else %}
      <h4>У вас ещё нет избранных подписок</h4>
    {% endif %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{ group }}</h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи
          группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Детальный просмотр{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <br>
              <a href="{% url 'posts:group_list' post.group.slug %}">
                Все записи группы {{ post.group }}
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.username }}
          </li>
          <li class="list-group-item d-flex
        justify-content-between align-items-center">
            Всего постов автора: <span>{{ posts_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              Все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}" alt="">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.author.username == user.username %}
          <a class="btn btn-primary"
             href="{% url 'posts:post_edit' post.pk %}">
            Редактировать запись
          </a>
        {% endif %}
        {% include 'includes/comments.html' %}
      </article>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ user.username }}{% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ post_count }}</h3>
    {% if request.user.username != author.username %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}"
          role="button">
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}"
          role="button">
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    <hr>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи
          группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}